# Site
name: "Technorage"
title: "Technorage"
description: "Where I rage about technology and stuff!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'UA-74370272-1'
disqus: 'deepu-tech'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  deepu:
    name: Deepu
    display_name: Deepu K Sasidharan
    gravatar: 7f408bc67dc9ae3b288ee92d16d3c4c2 # md5 hash of d4udts@gmail.com
    email: deepu.k.sasidharan@gmail.com
    web: https://www.deepu.tech
    twitter: https://twitter.com/deepu105
    description: "JHipster co-lead, Java, JS, Cloud Native Advocate, Dev @ XebiaLabs, Author, Speaker, Software craftsman. Loves simple & beautiful code. bit.ly/JHIPSTER-BOOK"

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-gist
  - jekyll-youtube

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: "deepu"

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - changelog.md
  - LICENSE.txt
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - mediumish-theme-jekyll
